version: '3.7'
services:
  mysql:
    image: mariadb:10.6.17
    container_name: mysql
    restart: always
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - infokes
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-ppassword'
      retries: 3
      timeout: 5s
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=password
      - UPLOAD_LIMIT=300M
    networks:
      - infokes
networks:
  infokes:
    driver: bridge
volumes:
  mysql_volume:
